### PR TITLE
Remove the old GCP account managers

### PR DESCRIPTION
**Pull request by josephlewis42**
The GCP Service Broker used the builtin/account_managers types to create Google Service Accounts and grant them IAM permissions. This isn't necessary in a universal brokerpak based system.

This PR removes most of the remaining deprecated providers/builtin components and associated testing for builtin providers (of which there are none left).

### CODE REVIEW

**Comment by blgm** [comment]
Thank you @josephlewis42!

Are you able to sign the CLA agreement as per the [comment above](https://github.com/cloudfoundry-incubator/cloud-service-broker/pull/226#issuecomment-819608392)?

**Comment by josephlewis42** [comment]
Hi @blgm,

My company has signed the CLA, but it looks like something has gone wrong with the bot. We've escalated on the CFF side to see what's up.

I have a couple of additional robustness improvements I'd like to contribute in the upcoming week, but if we can't get them in here, I can probably push to the gcp-service-broker where they can be forked again by any well-meaning projects based on its code :-)

**Comment by josephlewis42** [comment]
CLA signed! Is there a way to rev the go build process or is it stuck because of conflicts?

**Review by blgm — APPROVED** [review]

**Comment by blgm** [comment]
Thank you @josephlewis42!

**Pull request merged**
